### PR TITLE
Use ADB helpers to wait for activities

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/appium/issues/12414

ADB is better in detecting activities than pure instrumentation methods

### CODE REVIEW

**Comment by dpgraham** [comment]
Breaking these tests: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=1510&view=logs&jobId=25e09710-041d-5e84-9b7c-7583b448ad52&taskId=e24a952c-7148-505d-9805-c81d8eedb66c&lineStart=84&lineEnd=97&colStart=2&colEnd=89

```
 17 passing (115ms)
  2 failing

  1) driver
       startEspressoSession
         should call setHiddenApiPolicy:
     TypeError: Cannot read property 'appWaitActivity' of undefined
      at EspressoDriver.appWaitActivity [as startEspressoSession] (lib/driver.js:287:63)

  2) driver
       startEspressoSession
         should not call setHiddenApiPolicy:
     TypeError: Cannot read property 'appWaitActivity' of undefined
      at EspressoDriver.appWaitActivity [as startEspressoSession] (lib/driver.js:287:63)
```

**Comment by mykola-mokhnach** [comment]
@dpgraham yes I see, working on that.

**Comment by mykola-mokhnach** [comment]
The failing Travis tests seem to be caused by Travis slowness

**Comment by dpgraham** [comment]
@mykola-mokhnach yep... the AP tests cover the same thing, so I'm fine with committing this.

**Pull request merged**
