### PR TITLE
Added router to server

### PR DESCRIPTION
**Pull request by dpgraham**
* Moved Espresso into normal dependencies instead of test dependencies
* Added models, http, router, exceptions to main project
* Wrote a simple router that maps URI + Method to a handler
* Wrote one handler that takes a ‘selector’ queryString and then looks for an element that has a matching content-desc

### CODE REVIEW

**Comment by imurchie** [comment]
What was behind the decision to move all this into the App instead of the Test? I personally would opt for the App being a skeleton that does nothing (indeed, we shouldn't even need to install it), and everything happening in the test.

**Comment by dpgraham** [comment]
Because I want to be able to write tests for it and it would be confusing if we had tests that imported test code. Also I don't think that we could do code coverage analysis.

Technically, I don't think it makes a difference being inside the app folder. The code that is in `app` doesn't actually get imported by MainActivity, it only gets imported by the test file.

**Comment by imurchie** [comment]
I'm not sold.

Why not have it in a library, then, instead of in the app that doesn't use it?

**Comment by dpgraham** [comment]
Changes made

**Pull request merged**
