### PR TITLE
Drawable and Lifecycle issues fix (#449)

### PR DESCRIPTION
**Pull request by uterator**
The change has been done based on #449 discussions. 
It addresses the errors with [Drawable](https://github.com/appium/appium-espresso-driver/issues/449#issuecomment-525894658) and [Lifecycle](https://github.com/appium/appium-espresso-driver/issues/449#issuecomment-548080470)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@dpgraham Do you have any ideas about what happened to `PointerDispatchTest`? Is it just flaky?

**Comment by mykola-mokhnach** [comment]
@uterator Thanks for the PR

Do you know why https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=6145 fails with `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/material/navigation/NavigationView;` error? It looks like this error is caused by the changes done in the PR

**Comment by dpgraham** [comment]
@mykola-mokhnach I'll look at it over the weekend. I need to get Espresso Driver and Appium Desktop sorted out.

**Comment by dpgraham** [comment]
@mykola-mokhnach yeah you're right actually, I think it's from the PR.

Thanks for submitting this @uterator@ Do you know why this would happen ^ (java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/material/navigation/NavigationView)

**Comment by KazuCocoa** [comment]
Perhaps the below? It has a dependency to `NavigationView`

```
androidTestImplementation("androidx.test.espresso:espresso-contrib:$espresso_version") {
    transitive = false
}
```

**Comment by mykola-mokhnach** [comment]
@uterator Is there any chance to fix the PR?

**Comment by uterator** [comment]
> @uterator Is there any chance to fix the PR?

Hi @mykola-mokhnach, I haven't check yet but actually I don't have a good idea how to fix that. At this moment I can't put time on it so if someone can have a look on it it will be great help.

**Comment by blane1988** [comment]
Any updates to this?

**Comment by mykola-mokhnach** [comment]
@grzegorz-jarosz Could you please raise a new PR with this fix included?

**Pull request closed without merging**
