### PR TITLE
fix missing manifest

### PR DESCRIPTION
**Pull request by KazuCocoa**
Fix https://github.com/appium/appium/issues/11525#issuecomment-431633469

The cause is missing `espresso-server/AndroidManifest-test.xml` in npm package, it looks.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Could you take a look and update the npm package again? @dpgraham

**Comment by mykola-mokhnach** [comment]
There should be a way to prevent such issues in the future. We should either improve `copyFile`, so it throws a proper error if the source does not exist or add some verification into buildModServer method (less prefererable).

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Thank you for your investigation

**Comment by KazuCocoa** [comment]
Agree 👍  https://github.com/appium/appium-espresso-driver/pull/256#issuecomment-431646541

**Pull request merged**
