### PR TITLE
docs: Fix erroneous app description

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Espresso driver, actually, does not support .apks format. Related to https://github.com/appium/appium-espresso-driver/issues/713

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by KazuCocoa** [comment]
Probably can we support `.apks` once we add the ext in https://github.com/appium/appium-espresso-driver/blob/006bcfcf5a4d07713cb3e6d7a032ce80704cf28d/lib/driver.js#L177 ?

Let me test later if only the change help.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa I assume it won't work. The apk then must be patched with espresso server stuff to actually be able to run a test

**Comment by KazuCocoa** [comment]
yea, like this, probably like this customization will be needed. (need to ensure this tho)
mm, we need a better testing app for the appbundle.
https://stackoverflow.com/questions/60709733/create-unit-and-instrumentation-test-for-android-project-with-dynamic-features

**Comment by rajdeepv** [comment]
We can use `.apks` with espresso driver.  After unzipping `.apks`, use `splits/base-master.apk` to get the package and launch activity. Also signing info can be provided by the user to create espresso-server and it will work.

**Pull request merged**
