### PR TITLE
fix: Changes in build.gradle dependencies to overcome Resources$NotFoundException

### PR DESCRIPTION
**Pull request by rasim-sitmanbetov**
Hi,

Next few changes required for integration of **espresso-server** with our AUT to overcome Resources$NotFoundException.

These changes look to be AUT specific, and unfortunately I'm not sure it won't affect integration of **espresso-server** with other AUTs, having different dependencies/versions.

Please consider the changes in this PR and lets compare them with changes having similar idea in the https://github.com/appium/appium-espresso-driver/pull/596, https://github.com/appium/appium-espresso-driver/pull/506/files (apart from 
```    
androidTestImplementation("androidx.test.espresso:espresso-contrib:$espresso_version") {
        transitive = false
    }
``` 
which look to be common issue for all affected AUT). I've provided more details in the [comment](https://github.com/appium/appium-espresso-driver/issues/449#issuecomment-700061068)

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Could you resolve the conflict?

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
It looks like tests got unhappy after this change

**Comment by rasim-sitmanbetov** [comment]
@mykola-mokhnach 
the only change compared to the previous version with conflicts is version of `com.google.android.material:material`: `1.2.0` vs `1.2.1`.
Do you think it might be the reason?
- SDK 23 https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=11579&view=logs&j=b153b32a-4de0-56a1-d22c-0fe9139e49ff&t=36e351fe-dab4-56c5-ef36-3fbd0e352261&l=10775
- SDK 25 https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=11579&view=logs&j=66f1e43a-163e-5d1c-9c47-72628325f4ea&t=008bcb07-7c10-5131-8817-170e8f15b1fa&l=10702
- SDK 30 https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=11579&view=logs&j=e9fa3c63-21ed-5730-b945-3cceafbe7f30&t=651403d0-3420-5784-3a62-c1b43ce9a6b6&l=11243
failed 1 test:
```
1) mobile
       mobile: navigateTo
         should call the navigateTo method:
     AssertionError: expected promise to be rejected with an error matching /Could not navigate to menu item 10/ but got '[execute("mobile: navigateTo",{"element":{"ELEMENT":"af3731f3-9118-4117-9278-b571854b9ee2"},"menuItemId":10})] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/material/navigation/NavigationView;'
```
- SDK 29 https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=11579&view=logs&j=ea3a8326-8ae1-5392-57d8-7054c454cdab&t=bf55eb97-8c00-5287-3ece-aba70d92322c&l=11104
31 failing

I'm not very familiar with those tests. Could you please give me a hint what could went wrong?

**Comment by mykola-mokhnach** [comment]
I would say it is an issue with the Google's implementation of navigateTo action. It requires `import com.google.android.material.navigation.NavigationView;` to be imported. Although, I think this espresso server project itself should be import as little modules as possible. That is why it would make sense to delete `com.google.android.material` from the gradle file and add it to the `additionalAppDependencies` config entry of this particular test.
Also, I'll add a better handler for such type of exceptions, so people know what to do when it happens

**Comment by howsyourface** [comment]
We 100% need to get these application under test related dependencies out of there and use the mechanism provided. If that doesn't do it and it needs to be more configurable then we need to build in a bit more of a custom dependency management system into it.

This change has broken my apps, we need the:

```
androidTestImplementation("androidx.test.espresso:espresso-contrib:$espresso_version") {
        transitive = false
    }
```

But need to remove:

`androidTestImplementation "com.google.android.material:material:1.2.0"
`

As it seems to cause runtime exceptions in the application under test if it uses appcompat themes

**Comment by rasim-sitmanbetov** [comment]
Considering comments of @mykola-mokhnach and @howsyourface and already opened PR https://github.com/appium/appium-espresso-driver/pull/616, I think current PR should be closed.

FYI @grzegorz-jarosz as initially `androidTestImplementation "com.google.android.material:material:1.2.0"` was added in your PR https://github.com/appium/appium-espresso-driver/pull/596. I think after PR https://github.com/appium/appium-espresso-driver/pull/616 you will need to update your **espressoBuildConfig** with **additionalAppDependencies**

**Comment by grzegorz-jarosz** [comment]
I was having some doubts adding 'material' dependency, but didn't want to break existing tests. If we can fix this particular test then I guess it's fine.
I'm glad there's a light in the tunnel to have it solved for our users and I agree that less imported modules is better.
@rasim-sitmanbetov : Thank you, will keep an eye on the updates.

**Pull request closed without merging**
