### PR TITLE
chore: Gradle Version Updated to 6.5

### PR DESCRIPTION
**Pull request by ephelsa**
Solve this bug:

Captura de Pantalla 2020-11-05 a la(s) 11 04 35 p  m

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Could you please sign the CLA?

**Comment by ephelsa** [comment]
> Could you please sign the CLA?

Done

**Comment by KazuCocoa** [comment]
It seems you should fix 9145919 's commit email address as you signed one or sign CLA with the committed email address
@ephelsa

**Comment by ephelsa** [comment]
> It seems you should fix [9145919](https://github.com/appium/appium-espresso-driver/commit/914591924c633d3f86d8bffa52637870d818ec29) 's commit email address as you signed one or sign CLA with the committed email address
> @ephelsa

My bad. I made that commit with another laptop 😅


Captura de Pantalla 2020-11-07 a la(s) 11 29 10 a  m

**Review by mykola-mokhnach — APPROVED** [review]

**Pull request merged**
