### PR TITLE
Update text retrieval algorithm

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
CharSequence is an interface, which could contain any instance, which implements it. It would be safer to return a simple String instead. Also, the text getting procedure itself should be common across the code.

See https://github.com/appium/ruby_lib/issues/598#issuecomment-393713265 for more details.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@KazuCocoa FYI

**Comment by KazuCocoa** [comment]
@mykola-mokhnach 
🆒 
The `getText` works!

But I faced another issue. When I run `type`, then exception is inputted by `replaceText`.
If the `type` is `e.type 'normal'`, for example, it worked fine.


## Logcat
```
06-01 13:46:50.982 17957-17962/com.android.systemui I/zygote: After code cache collection, code=124KB, data=81KB
    Increasing code cache capacity to 512KB
06-01 13:46:54.565 20316-20372/io.appium.android.apis D/appium: Started processing POST request to '/session/8f098e45-4f57-4254-8ccb-45f5e49292ba/element/1f762585-f071-4f35-902c-04e4afb70c1b/value'
06-01 13:46:54.566 20316-20372/io.appium.android.apis D/appium: Matched route handler: class io.appium.espressoserver.lib.handlers.SendKeys
06-01 13:46:54.567 20316-20372/io.appium.android.apis D/appium: Got raw post data: {"value":["P","ö","k","é","m","ö","n"],"text":"Pökémön"}
06-01 13:46:54.575 20316-20316/io.appium.android.apis I/ViewInteraction: Checking 'MatchesViewAssertion{viewMatcher=is displayed on the screen to the user}' assertion on view Looked for element with View android.widget.EditText{20cfc02 VFED..CL. .F...... 0,0-550,126 #7f0b006d app:id/left_text_edit}
06-01 13:46:54.581 20316-20372/io.appium.android.apis I/appium: Retrieving element 1f762585-f071-4f35-902c-04e4afb70c1b
06-01 13:46:54.596 20316-20316/io.appium.android.apis I/ViewInteraction: Checking 'MatchesViewAssertion{viewMatcher=is displayed on the screen to the user}' assertion on view Looked for element with View android.widget.EditText{20cfc02 VFED..CL. .F...... 0,0-550,126 #7f0b006d app:id/left_text_edit}
06-01 13:46:54.606 20316-20316/io.appium.android.apis I/ViewInteraction: Performing 'type text(Pökémön)' action on view Looked for element with View android.widget.EditText{20cfc02 VFED..CL. .F...... 0,0-550,126 #7f0b006d app:id/left_text_edit}
06-01 13:46:54.706 1379-1432/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 45056
06-01 13:46:54.707 1379-12012/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 45056
06-01 13:46:54.710 1379-12012/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 45056
06-01 13:46:54.741 20316-20338/io.appium.android.apis D/EGL_emulation: eglMakeCurrent: 0xa1d86020: ver 3 0 (tinfo 0xa1d83af0)
06-01 13:46:55.003 20316-20372/io.appium.android.apis D/appium: Trying replaceText action as a workaround to type the 'Pökémön' text into the input field
06-01 13:46:55.008 20316-20316/io.appium.android.apis I/ViewInteraction: Performing 'getting view in application' action on view Looked for element with View android.widget.EditText{20cfc02 VFED..CL. .F...... 0,0-550,126 #7f0b006d app:id/left_text_edit}
06-01 13:46:55.012 20316-20372/io.appium.android.apis D/appium: Current input field's text: 'io.appium.espressoserver.lib.model.ViewText@9485fd6'
06-01 13:46:55.017 20316-20316/io.appium.android.apis I/ViewInteraction: Performing 'replace text' action on view Looked for element with View android.widget.EditText{20cfc02 VFED..CL. .F...... 0,0-550,126 #7f0b006d app:id/left_text_edit}
06-01 13:46:55.021 20341-20341/io.appium.android.ime I/AppiumUnicodeIME: onStartInput
06-01 13:46:55.031 1575-1589/system_process E/memtrack: Couldn't load memtrack module
06-01 13:46:55.031 1575-1589/system_process W/android.os.Debug: failed to get memory consumption info: -1
06-01 13:46:55.035 20316-20338/io.appium.android.apis D/EGL_emulation: eglMakeCurrent: 0xa1d86020: ver 3 0 (tinfo 0xa1d83af0)
06-01 13:46:55.041 20316-20372/io.appium.android.apis D/appium: Finished processing POST request to '/session/8f098e45-4f57-4254-8ccb-45f5e49292ba/element/1f762585-f071-4f35-902c-04e4afb70c1b/value'
06-01 13:46:55.042 20316-20372/io.appium.android.apis I/appium: Responding to server with value: null
06-01 13:46:55.047 20316-20338/io.appium.android.apis D/EGL_emulation: eglMakeCurrent: 0xa1d86020: ver 3 0 (tinfo 0xa1d83af0)
```

## server
```
[HTTP]
[HTTP] --> POST /wd/hub/session/76762a7a-718a-4fbf-989c-297a89391770/element/1f762585-f071-4f35-902c-04e4afb70c1b/value
[HTTP] {"value":["P","ö","k","é","m","ö","n"],"text":"Pökémön"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/76762a7a-718a-4fbf-989c-297a89391770/element/1f762585-f071-4f35-902c-04e4afb70c1b/value] to [POST http://localhost:8080/session/8f098e45-4f57-4254-8ccb-45f5e49292ba/element/1f762585-f071-4f35-902c-04e4afb70c1b/value] with body: {"value":["P","ö","k","é","m","ö","n"],"text":"Pökémön"}
[debug] [JSONWP Proxy] Got response with status 200: {"id":"507133c8-383d-4992-85a6-518e9b13dfad","sessionId":"8f098e45-4f57-4254-8ccb-45f5e49292ba","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 8f098e45-4f57-4254-8ccb-45f5e49292ba with 76762a7a-718a-4fbf-989c-297a89391770
[HTTP] <-- POST /wd/hub/session/76762a7a-718a-4fbf-989c-297a89391770/element/1f762585-f071-4f35-902c-04e4afb70c1b/value 200 497 ms - 120
[HTTP]
[debug] [ADB] Running '/Users/kazuaki/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am instrument -w -e debug false io.appium.espressoserver.test/android.support.test.runner.AndroidJUnitRunner'
```

## Ruby

```
e = @@core.wait { @@driver.find_element :id, 'io.appium.android.apis:id/left_text_edit' }
e.type 'Pökémön'
```

|before|after| _normal text_ |
|:----:|:----:| :----: |
|image|image|image|

**Comment by KazuCocoa** [comment]
I ran with 44dd0e7

**Comment by mykola-mokhnach** [comment]
Thanks for checking it @KazuCocoa . The issue above should be fixed now

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-espresso-driver/pull/146#issuecomment-393888414 was fixed in aef0236 👍 
@mykola-mokhnach

**Pull request merged**
